
DROP TABLE ODONTOLOGOS IF EXISTS;
CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
MATRICULA INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL
);


INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 202407, 'JUAN', 'PEREZ');
INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 202012, 'MARCELO', 'BRAVO');